config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # 会員認証ルーティング
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # root_path
  root to: 'public/homes#top'

  # 会員ルーティング
  scope module: :public do
    get '/about' => 'homes#about', as: 'about'

    resources :members, only: [:show, :edit, :index, :update]
    get 'members/:id/unregistration' => 'members#unregistration', as: 'member_unregistration'
    patch 'members/:id/withdrawal' => 'members#withdrawal', as: 'member_withdrawal'

    resources :events, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    patch 'events/:id/status' => 'events#status', as: 'event_status'
  end


  # 管理者認証ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # 管理者ルーティング
  namespace :admin do
    get '/' => 'homes#top'
    resources :members, only: [:show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :events, only: [:index, :show]
  end
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :member
    belongs_to :genre

    validates :name, presence: true
    validates :introduction, presence: true
    validates :start_at, presence: true
    validates :end_at, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    # 降順で, 20件ごとにページネーション
    @events = Event.all.order(id: "DESC").page(params[:page]).per(20)
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_index.html.erb
<div class="card-list-container py-5">
  <% events.each do |event| %>
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <div class="card-body">
        <div class="row">
          <div class="col-3 mr-5">
            <%= link_to(admin_member_path(event.member), class:"text-dark") do %>
              <%= image_tag event.member.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
              <span><i class="fa-solid fa-user"></i> <%= event.member.name %></span>
            <% end %>
          </div>
          <div class="col-7 ml-5">
            <%= link_to(admin_event_path(event.id), class:"text-dark") do %>
              <p class="card-title"> <strong><i class="far fa-flag"></i><span> <%= event.name %></span></strong></p>
              <p class="card-text"><i class="fa-solid fa-tag"></i> <%= event.genre.name %></p>
              <p class="card-text"><i class="fa-regular fa-clock"></i> <%= event.start_at %> ~ <%= event.end_at %></p>
              <p class="card-text">
                <% if event.is_done %>
                    <p class="h5 text-success">完了</p>
                <% else %>
                    <p class="h5 text-danger">未済</p>
                <% end %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!--降順で, 20件ずつページネーション-->
  <%= paginate events, theme: 'bootstrap-5' %>
</div>

app/views/admin/events/index.html.erb
<div class="col-12 text-center">
    <h4 class="p-3 border-bottom">みんなのイベントTODO</h4>
</div>

<%= render 'index', events: @events %>

app/views/admin/events/show.html.erb
<h4 class="p-3 border-bottom text-center">イベントTODO詳細</h4>

<div class="col-4">
    <div class="pt-4 pl-5">
    <h6><i class="fa-solid fa-user"></i> 投稿ユーザー</h6>
    <%= link_to(admin_member_path(@event.member), class:"text-dark") do %>
        <%= image_tag @event.member.get_profile_image(150,150), class:"mt-3 rounded-circle"; %>
        <p class="h5"><%= @event.member.name %></p>
    <% end %>
    </div>
</div>

<div class="col-8">
    <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="far fa-flag"></i> イベント名:</h6>
        <p class="h5"><%= @event.name %></p>
    </div>

    <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-regular fa-clock"></i> イベント開催日程:</h6>
        <p class="h5"><%= @event.start_at %> ~ <%= @event.end_at %></p>
    </div>

    <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-solid fa-pen-fancy"></i> イベント詳細:</h6>
        <p class="h5"><%= @event.introduction %></p>
    </div>

    <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-solid fa-tag"></i> ジャンル:</h6>
        <p class="h5"><%= @event.genre.name %></p>
    </div>

    <div class="p-3 w-75">
        <h6 class="border-bottom"><i class="fa-solid fa-check"></i> 完了状態:</h6>
        <% if @event.is_done %>
            <p class="h5 text-success">完了</p>
        <% else %>
            <p class="h5 text-danger">未済</p>
        <% end %>
    </div>
</div>