config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # 会員認証ルーティング
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # root_path
  root to: 'public/homes#top'

  # 会員ルーティング
  scope module: :public do
    get '/about' => 'homes#about', as: 'about'

    resources :members, only: [:show, :edit, :index, :update]
    get 'members/:id/unregistration' => 'members#unregistration', as: 'member_unregistration'
    patch 'members/:id/withdrawal' => 'members#withdrawal', as: 'member_withdrawal'

    resources :events, only: [:new, :index, :show, :edit, :create, :update, :destroy]
    patch 'events/:id/status' => 'events#status', as: 'event_status'
  end


  # 管理者認証ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # 管理者ルーティング
  namespace :admin do
    get '/' => 'homes#top'
    resources :members, only: [:show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :events, only: [:index, :show]
  end
end

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">

      <% if admin_signed_in? %>
        <h1 style="font-family: cursive;"><%= link_to "Eventare", admin_path, class: 'navbar-brand p-3' %></h1>
      <% else %>
        <h1 style="font-family: cursive;"><%= link_to "Eventare", root_path, class: 'navbar-brand p-3' %></h1>
      <% end %>

      <% if member_signed_in? %>
        <%= render 'public/shared/search_bar' %>
      <% end %>
      
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-users"></i> 会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_events_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-calendar-days"></i> イベント一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-tag"></i> ジャンル一覧
            <% end %>
          </li>
          
          <li class="nav-item">
            <%= button_to destroy_admin_session_path, method: :delete, form: { data: { turbo_confirm: "本当にログアウトしますか？" } }, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt" aria-hidden="true"></i> ログアウト
            <% end %>
          </li>

        <% elsif member_signed_in? %>
          <li class="nav-item">
            <%= link_to members_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-users"></i> 会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to events_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-globe"></i> みんなのTODO
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to member_path(current_member), class: 'nav-link text-dark' do %>
              <i class="fas fa-user" aria-hidden="true"></i> マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to destroy_member_session_path, method: :delete, form: { data: { turbo_confirm: "本当にログアウトしますか？" } }, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt" aria-hidden="true"></i> ログアウト
            <% end %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to about_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-link" aria-hidden="true"></i> 概要
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_member_registration_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus" aria-hidden="true"></i> 新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_member_session_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-right-to-bracket"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_validation.html.erb
<% if obj.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= obj.errors.count %>件のエラーが発生しました
    </h6>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/64316cd30c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>

    <%= render "layouts/header" %>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-success"><%= message %></div>
    <% end %>
    
    <div class="container mt-5">
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
</html>